// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Name;
extern lv_obj_t * ui_Fans;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bilibili_png);    // assets\bilibili.png
LV_IMG_DECLARE(ui_img_bilibiliname_png);    // assets\bilibiliName.png

LV_FONT_DECLARE(ui_font_PHFont16);
LV_FONT_DECLARE(ui_font_PHFont18);
LV_FONT_DECLARE(ui_font_PHFont20);
LV_FONT_DECLARE(ui_font_PHFont22);
LV_FONT_DECLARE(ui_font_PHFont24);
LV_FONT_DECLARE(ui_font_PHFont26);
LV_FONT_DECLARE(ui_font_PHFont30);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
